services:
  pgdatabase:
    image: postgres:18
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - "ny_taxi_postgres_data:/var/lib/postgresql"
    ports:
      - "5432:5432"
    restart: unless-stopped
    network_mode: host          # ⬅️ THÊM DÒNG NÀY

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_LISTEN_PORT: 8085   # ⬅️ pgAdmin sẽ nghe trên port 8085
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    volumes:
      - "pgadmin_data:/var/lib/pgadmin"
    restart: unless-stopped
    network_mode: host          # ⬅️ THÊM DÒNG NÀY

volumes:
  ny_taxi_postgres_data:
  pgadmin_data: